# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "course_registrations", :force => true do |t|
    t.column "course_version_id", :integer
    t.column "year_id",           :integer
  end

  create_table "course_versions", :force => true do |t|
    t.column "course_id", :integer
  end

  create_table "courses", :force => true do |t|
    t.column "name",       :string, :limit => 128
    t.column "code",       :string, :limit => 10
    t.column "points",     :float
    t.column "objectives", :text
    t.column "contents",   :text
  end

  create_table "locations", :force => true do |t|
    t.column "course_version_id",   :integer
    t.column "timetable_module_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "studyplans", :force => true do |t|
    t.column "user_id", :integer
  end

  create_table "timetable_modules", :force => true do |t|
    t.column "name", :string,  :limit => 3
    t.column "fall", :boolean
  end

  create_table "users", :force => true do |t|
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "email",           :string
  end

  create_table "years", :force => true do |t|
    t.column "studyplan_id", :integer
    t.column "title",        :string
  end

end
